### ISSUE TITLE
How to access cubic spline of a corridor

### ISSUE THREAD

**Issue by orzechow** [dspetrich/corridor#1]
First of all, thanks @dspetrich for this great library and your talk at our institute! I'm considering using it in my planning stack :)

After checking your headers and examples, I'm wondering:
What is the intended way to access the cubic spline reference line of a corridor, namely the [`reference_line_`](https://github.com/dspetrich/corridor/blob/master/include/corridor/corridor.h#L122)? Wouldn't it make sense to expose [`reference_line_`](https://github.com/dspetrich/corridor/blob/master/include/corridor/corridor.h#L122) with a const getter function?

The application I have in mind is creating a corridor object from a given lanelet sequence and resample a smoothed version of the reference line, e.g. as an initialization path for trajectory planning, predition, …

**Comment by dspetrich** [comment]
Hi Piotr,
glad to hear that you liked it. 

To answer your question:
The intention was to not bother the consumer of a corridor with the definition of the reference line ;-)
However, if you need direct access to it please feel free to add it. 

Maybe you could elaborate why you need direct access to it? Its possible that the needed information is already available to you. 
For instance carries the Frenet Frame, which can be constructed at any given Cartesian position, all geometric information of the curve at that point, like arc-length, curvature, curvature-changing-rate,  origin, tangent, normal etc.

**Comment by dspetrich** [comment]
To resample the reference line (and boundaries) you can call _fillCartesianPolylines()_ as well.

The returned reference line polyline can then be used to construct another cubic spline.

Maybe that's already what you were looking for?

**Comment by orzechow** [comment]
Thanks, `fillCartesianPolylines()` is actually nearly what I am looking for.
I agree to sparing the user from to much internal stuff, so I added a small modification from `fillCartesianPolylines()` that does the sampling only for the reference line, not the bounds (for efficiency reasons): #3 

One of the use cases I am thinking of is having multiple objects or even ROS each node planning distinct maneuvers (like lane change, follow ego lane, …). Each would then do:

- Read road geometry from lanelet map
- Convert to a nice spline based representation with this lib
- Do some planning and use the spline-version of the reference line, e.g.
  - as an initialization in the trajectory planner or
  - as the path of a simplistic simulated agent doing only IDM along predefined paths (for our [coincar-sim](https://github.com/coincar-sim/))

For such cases, `fillCartesianPolylines()` or `fillCartesianReferencePolyline()` does exactly this job :ok_hand:

**Comment by dspetrich** [comment]
Alright sounds good and the PR looks good as well.
Thanks for your contribution!

**Comment by orzechow** [comment]
No problem, thanks for the nice lib :)
