### ISSUE TITLE
Segfault with duplicate points in reference line

### ISSUE THREAD

**Issue by orzechow** [dspetrich/corridor#5]
I just realized with one of our lanelet2 maps that instanciating a `Corridor` object results in a segmentation fault if the reference line contains duplicate points.
That is because the delta arc lengths in [`ClampedSplineMatrixL()`](https://github.com/dspetrich/corridor/blob/master/src/cubic_interpolation_2d.cpp#L169) become zero.

I don't know if you want to catch duplicate points or mention that assumption in the Readme or so, but I guess it helps letting you know that lanelet2 does not forbid duplicate points in a linestring, so that could happen to all people using lanelet2.
For me, I solved it by removing duplicates before creating the `Corridor` object.

**Comment by orzechow** [comment]
Btw. an efficient method to remove neighboring duplicates in a vector without messing up the order [1]:

```c++
auto last = std::unique(linestring->begin(), linestring->end());
linestring->erase(last, linestring->end());  
```

[1] https://devdocs.io/cpp/algorithm/unique

**Comment by dspetrich** [comment]
Hi @orzechow, 
correct, the corridor library requires that the reference line doesn't contain duplicate points. 
Actually I assumed that I added it to the description, but couldn't find it. I will add it right away together with your hint how to remove duplicates. 
Thanks for the hint!

**Comment by dspetrich** [comment]
Hi @orzechow, I adapted the readme to include the hint regarding the duplicated points. Please have a look.

**Comment by orzechow** [comment]
Thanks, that should help :)
